import { Inter, Roboto } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Chatbot from "@/components/Chatbot";

const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({
  weight: ['400', '700'],
  subsets: ['latin']
})

export const metadata = {
  title: {
    template: '%s | Blog by Volodymyr Varakin',
    default: 'Blog by Volodymyr Varakin'
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body className={roboto.className}>

        <Header />
          <main className="mt-12">
            {children}
          </main>

          <Chatbot />
        </body>
    </html>
  );
}
